# Generated by Django 2.0.6 on 2018-06-29 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Banda')),
            ],
            options={
                'verbose_name': 'Banda',
                'verbose_name_plural': 'Bandas',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da música')),
                ('duration', models.DurationField(verbose_name='Duração da música')),
                ('release', models.DateField(blank=True, verbose_name='Data de Lançamento')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Band', verbose_name='Banda')),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Músicas',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Playlist')),
                ('music', models.ManyToManyField(to='music.Music', verbose_name='Música')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Gravadora')),
            ],
            options={
                'verbose_name': 'Gravadora',
                'verbose_name_plural': 'Gravadora',
            },
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Genre', verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='band',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Record', verbose_name='Gravadora'),
        ),
    ]
