Insert into Pedido (idpedido, Nrpedido,idcliente)  values(1, 1, 1);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(2, 2, 1);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(3, 3, 1);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(4, 4, 1);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(5, 5, 1);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(6, 6, 1);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(7, 7, 1);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(8, 8, 1);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(9, 9, 1);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(10, 10, 2);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(11, 11, 2);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(12, 12, 2);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(13, 13, 2);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(14, 14, 2);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(15, 15, 2);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(16, 16, 2);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(17, 17, 3);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(18, 18, 3);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(19, 19, 3);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(20, 20, 3);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(21, 21, 3);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(22, 22, 3);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(23, 23, 3);
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(24, 24 , 2 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(25, 25 , 2 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(26, 26 , 2 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(27, 27 , 2 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(28, 28 , 2 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(29, 29 , 2 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(30, 30 , 2 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(31, 31 , 1 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(32, 32 , 1 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(33, 33 , 1 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(34, 34 , 1 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(35, 35 , 1 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(36, 36 , 1 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(37, 37 , 1 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(38, 38 , 1 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(39, 39 , 1 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(40, 40 , 3 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(41, 41 , 3 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(42, 42 , 3 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(43, 43 , 3 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(44, 44 , 3 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(45, 45 , 3 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(46, 46 , 3 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(47, 47 , 3 );
Insert into Pedido (idpedido, Nrpedido,idcliente)  values(48, 48 , 3 );