Insert into Produto (Idproduto,Nome)  values( 1, 'ABACATE');
Insert into Produto (Idproduto,Nome)  values( 2,'ABO. ITALIANA');
Insert into Produto (Idproduto,Nome)  values( 3,'ABO. MENINA');
Insert into Produto (Idproduto,Nome)  values(4,'ABO. MOGANGA');
Insert into Produto (Idproduto,Nome)  values(5,'ABACAXI');
Insert into Produto (Idproduto,Nome)  values(6,'ALFACE');
Insert into Produto (Idproduto,Nome)  values(7,'ALHO BRASILEIRO');
Insert into Produto (Idproduto,Nome)  values(8,'BANANA-NANICA');
Insert into Produto (Idproduto,Nome)  values(9,'BANANA-PRATA');
Insert into Produto (Idproduto,Nome)  values(10,'BATATA');
Insert into Produto (Idproduto,Nome)  values(11,'BATATA-DOCE');
Insert into Produto (Idproduto,Nome)  values(12,'BERINJELA');
Insert into Produto (Idproduto,Nome)  values(13,'BETERRABA');
Insert into Produto (Idproduto,Nome)  values(14,'BROCOLO');
Insert into Produto (Idproduto,Nome)  values(15,'CEBOLA');
Insert into Produto (Idproduto,Nome)  values(16,'CENOURA');
Insert into Produto (Idproduto,Nome)  values(17,'CHUCHU');
Insert into Produto (Idproduto,Nome)  values(18,'COCO VERDE');
Insert into Produto (Idproduto,Nome)  values(19,'COUVE');
Insert into Produto (Idproduto,Nome)  values(20,'COUVE-FLOR');
Insert into Produto (Idproduto,Nome)  values(21,'ESPINAFRE');
Insert into Produto (Idproduto,Nome)  values(22,'GOIABA');
Insert into Produto (Idproduto,Nome)  values(23,'INHAME');
Insert into Produto (Idproduto,Nome)  values(24,'JILO');
Insert into Produto (Idproduto,Nome)  values(25,'LARANJA');
Insert into Produto (Idproduto,Nome)  values(26,'LIMAO');
Insert into Produto (Idproduto,Nome)  values(27,'MACA');
Insert into Produto (Idproduto,Nome)  values(28,'MAMAO-FORMOSA');
Insert into Produto (Idproduto,Nome)  values(29,'MAMAO-HAVAI');
Insert into Produto (Idproduto,Nome)  values(30,'MANDIOCA');
Insert into Produto (Idproduto,Nome)  values(31,'MANDIOQUINHA');
Insert into Produto (Idproduto,Nome)  values(32,'MANGA');
Insert into Produto (Idproduto,Nome)  values(33,'MARACUJA');
Insert into Produto (Idproduto,Nome)  values(34,'MELANCIA');
Insert into Produto (Idproduto,Nome)  values(35,'MELAO');
Insert into Produto (Idproduto,Nome)  values(36,'MILHO-VERDE');
Insert into Produto (Idproduto,Nome)  values(37,'MORANGA');
Insert into Produto (Idproduto,Nome)  values(38,'MORANGO');
Insert into Produto (Idproduto,Nome)  values(39,'OVOS');
Insert into Produto (Idproduto,Nome)  values(40,'PEPINO');
Insert into Produto (Idproduto,Nome)  values(41,'PERA');
Insert into Produto (Idproduto,Nome)  values(42,'PIMENTAO');
Insert into Produto (Idproduto,Nome)  values(43,'QUIABO');
Insert into Produto (Idproduto,Nome)  values(44,'REPOLHO');
Insert into Produto (Idproduto,Nome)  values(45,'TANGERINA');
Insert into Produto (Idproduto,Nome)  values(46,'TOMATE');
Insert into Produto (Idproduto,Nome)  values(47,'UVA');
Insert into Produto (Idproduto,Nome)  values(48,'VAGEM')